Clarify usage

diff --git a/sapebook2pdf b/sapebook2pdf
--- a/sapebook2pdf
+++ b/sapebook2pdf
@@ -4,39 +4,55 @@ usage() {
   cat <<EOF
 Generate a PDF from an SAP Learning Hub ebook. Their ebook reader is insulting.
 
-Usage scheme:
- - Login with your browser and open the ebook's index.html and generate the
-   cookies.txt
- - Locate the path to the ebook page's SVG files and use dlsvg() to download
-   all SVGs. Use your browser's page inspection tools.
- - List the SVG's required fonts using lsfonts() and install any missing
-   fonts. Some of the fonts may be downloaded from the ebook's server. Have a
-   look into the css (e.g. css/webFonts.css lists paths to webfonts). Downloaded
-   webfonts (.woff2 format) may be converted to .ttf via 'woff2_decompress'.
-   Missing fonts won't be included in the generated PDF causing a default font
-   to be used, which may mess up the document layout. No bueno.
- - Generate PDFs from SVGs using genpdf().
+Usage:
 
-WIP; Arguments not parameterized; Many Todos
+  $ZSH_ARGZERO [OPTIONS] SETTING=VALUE...
+
+    VALUEs must be provided for each of the following SETTINGs:
+
+      --baseurl - Path URL to the directory containing the ebook's index.html
+      --cookies - Path to local cookies.txt containing the login cookies
+      --pages   - Range of pages as two numbers separated by a hyphen
+      --pdfout  - Output path. Directory must exist.
+
+    OPTIONS include:
+
+      --nocheckfont - Don't check if all SVG fonts are availble on the system
+      --nocleanup   - Don't remove temporary files after finishing
+
+    Usage hints:
+
+      To acquire a cookies.txt login to your account and navigate to the ebook.
+      Use you browser to generate the cookies.txt for you (which may require a
+      using a plugin).
+
+      The baseurl corresponds to the path containing the index.html. Given
+      'https://sap.com/foo/self-managed/ebook/BC100_EN_Col18/index.html' the
+      baseurl is 'https://sap.com/foo/self-managed/ebook/BC100_EN_Col18/'.
+
+      The ebooks are stored online as individual pages in SVG format. These
+      SVGs reference fonts which are required to be available on your system
+      in order for them to end up in the generated PDF. The availability of
+      the fonts is asserted during compilation with missing fonts having to be
+      installed manually on your system. You may choose to skip any font
+      checks via the option --nocheckfont which will lead to the usage of
+      your system's fallback fonts which may of may produce a goofy PDF.
+
+
+Examples:
+
+  $ZSH_ARGZERO \\
+    --nocheckfont \\
+    --baseurl="https://sap.com/foo/self-managed/ebook/BC100_EN_Col18" \\
+    --pages=40-80 \\
+    --cookies=./cookies.txt \\
+    --pdfout=~/doc/ebook.pdf
 EOF
 }
 
-# Exported cookies.txt generated by Firefox.
-cookies="./cookies.txt"
-
-# Where to stuff all svgs. Directory will be created silently.
-tmpdir="/tmp/sapebook"
-
-# Final PDF output path. Directory will be created silently.
-pdfout="./ebook.pdf"
-
-# TODO: Retrieve number of pages dynamically from 'index.html'
-# Pages to extract. One page number per line.
-pages="$(seq 1 120)"
-
-# Base url with respect to which all resource paths are interpreted. Directory
-# of 'index.html'.
-baseurl="https://saplearninghub.plateau.com/icontent_e/CUSTOM_eu/sap/self-managed/ebook/BC100_EN_Col18"
+cleanup() {
+  rm -r "$tmpdir"
+}
 
 # Download all SVG files
 dlsvg() {
@@ -56,7 +72,7 @@ dlsvg() {
       echo "$reply" | head -n -1 > "$tmpdir/page$page.svg"
     fi
   done
-  printf "\n"
+    printf "\033[2K\rDownloading SVGs ... done.\n"
   if [ ! -z "$errorat" ]; then
     echo "$errorat" | while read page; do
       echo "Error downloading page(s) '${errorat:s/ //}'" >&2
@@ -67,11 +83,12 @@ dlsvg() {
 
 # List all fonts required inside the SVGs
 lsfonts() {
+  printf "Required fonts:\n"
   fonts="$(cat "$tmpdir/"*.svg | grep -o 'font-family="[^"]*"' |
     cut -d '=' -f 2- | sed -e 's/^"'"'"'\?//g' -e 's/'"'"'\?"$//g' |
     sort | uniq)"
   echo "$fonts" | while read f; do
-    printf "$f "
+    printf " - $f "
     if fc-list :family | grep -q "$f"; then
       printf "[\033[32mavailable\033[0m]\n"
     else
@@ -87,7 +104,7 @@ genpdf() {
   total="$(echo "$pages" | wc -l)"
   ii=1
   echo "$pages" | while read page; do
-    printf "\033[2K\rGenerating PDF pages from SVG ... $ii/$total"
+    printf "\033[2K\rGenerating single PDF pages from SVGs ... $ii/$total"
     ii=$((ii + 1))
     inf="$tmpdir/page$page.svg"
     outf="$tmpdir/page$page.pdf"
@@ -95,7 +112,7 @@ genpdf() {
       errorat="$errorat $page"
     fi
   done
-  printf "\n"
+    printf "\033[2K\rGenerating single PDF pages from SVGs ... done.\n"
   if [ ! -z "$errorat" ]; then
     echo "$errorat" | while read page; do
       echo "Error generating PDFs from SVG page(s) '${errorat:s/ //}'" >&2
@@ -104,7 +121,59 @@ genpdf() {
   fi
   inpdfs="$(echo "$pages" | sed 's|.*|'"$tmpdir/"'page&.pdf|g')" # in order
   mkdir -p "${pdfout:A:h}"
-  pdftk "${=inpdfs:s/\n/ }" cat output "$pdfout"
+  printf "Collating pages into single PDF '$pdfout' ... "
+  if pdftk "${=inpdfs:s/\n/ }" cat output "$pdfout"; then
+    printf "done.\n"
+  else
+    printf "error.\n"
+  fi
+}
+
+# Parse args and initialize globals
+setup() {
+  for arg in "$@"; do
+    if echo "$arg" | grep -q '^--pdfout='; then
+      pdfout="${arg:s/--pdfout=//}"
+    elif echo "$arg" | grep -q '^--cookies='; then
+      cookies="${arg:s/--cookies=//}"
+    elif echo "$arg" | grep -q '^--baseurl='; then
+      baseurl="${arg:s/--baseurl=//}"
+    elif echo "$arg" | grep -q '^--pages='; then
+      range="${arg:s/--pages=//}"
+      if ! echo "$range" | grep -q '^[1-9]\+[0-9]*-[1-9]\+[0-9]*'; then
+        echo "Invalid page range." >&2
+        return 1
+      fi
+      n="$(echo "$range" | cut -d '-' -f1)"
+      m="$(echo "$range" | cut -d '-' -f2)"
+      if [ $n -gt $m ] || [ $m -le 0 ]; then
+        echo "Invalid page range." >&2
+        return 1
+      fi
+      pages="$(seq $n $m)"
+    elif [ "$arg" = "--nocheckfont" ]; then
+      nocheckfont=1
+    elif [ "$arg" = "--nocleanup" ]; then
+      nocleanup=1
+    else
+      echo "Unrecognized parameter '$arg'." >&2
+      return 1
+    fi
+  done
+
+  if [ ! -r "$cookies" ]; then
+    echo "Cannot read cookies file '$cookies'."
+    return 1
+  fi
+  if [ ! -d "${pdfout:A:h}" ]; then
+    echo "Output directory '${pdfout:A:h}' does not exist."
+    return 1
+  fi
+  if ! tmpdir="$(mktemp -d)"; then
+    echo "Cannot create temporary directory."
+    return 1
+  fi
+  # TODO: Curl index.html and check connection
 }
 
 case "$1" in
@@ -117,8 +186,15 @@ case "$1" in
   ;;
 *)
   set -e
+  setup "$@"
+  printf "Temporary files are saved to '$tmpdir'.\n"
   dlsvg
-  lsfonts
+  if [ ! $nocheckfont ]; then
+    lsfonts
+  fi
   genpdf
+  if [ ! $nocleanup ]; then
+    cleanup
+  fi
   ;;
 esac
